name: ecommerce_warehouse
version: 1.0.0
config-version: 2

profile: ecommerce_clickhouse

model-paths: ["models"]
test-paths: ["tests"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  ecommerce_warehouse:
    staging:
      +materialized: ephemeral
    gold:
      +materialized: table
      +engine: MergeTree()
